from __future__ import annotations

import math
from pathlib import Path
from typing import Dict, List

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parent.parent
OUT_H = ROOT / "src" / "assets" / "font_assets.h"
OUT_C = ROOT / "src" / "assets" / "font_assets.c"
ASCII_START = 32
ASCII_END = 126

FONTS = [
    {
        "symbol": "ui_12",
        "role": "FONT_ROLE_UI",
        "size": 12,
        "path": ROOT / "assets" / "upstream" / "fonts" / "adwaita" / "AdwaitaSans-Regular.ttf",
    },
    {
        "symbol": "ui_16",
        "role": "FONT_ROLE_UI",
        "size": 16,
        "path": ROOT / "assets" / "upstream" / "fonts" / "adwaita" / "AdwaitaSans-Regular.ttf",
    },
    {
        "symbol": "ui_20",
        "role": "FONT_ROLE_UI",
        "size": 20,
        "path": ROOT / "assets" / "upstream" / "fonts" / "adwaita" / "AdwaitaSans-Regular.ttf",
    },
    {
        "symbol": "ui_24",
        "role": "FONT_ROLE_UI",
        "size": 24,
        "path": ROOT / "assets" / "upstream" / "fonts" / "adwaita" / "AdwaitaSans-Regular.ttf",
    },
    {
        "symbol": "ui_32",
        "role": "FONT_ROLE_UI",
        "size": 32,
        "path": ROOT / "assets" / "upstream" / "fonts" / "adwaita" / "AdwaitaSans-Regular.ttf",
    },
    {
        "symbol": "mono_13",
        "role": "FONT_ROLE_MONO",
        "size": 13,
        "path": ROOT / "assets" / "upstream" / "fonts" / "adwaita" / "AdwaitaMono-Regular.ttf",
    },
    {
        "symbol": "mono_16",
        "role": "FONT_ROLE_MONO",
        "size": 16,
        "path": ROOT / "assets" / "upstream" / "fonts" / "adwaita" / "AdwaitaMono-Regular.ttf",
    },
]


def c_bytes(data: List[int], indent: str = "    ", wrap: int = 16) -> str:
    lines = []
    for i in range(0, len(data), wrap):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i : i + wrap])
        lines.append(f"{indent}{chunk},")
    if not lines:
        lines.append(f"{indent}0x00,")
    return "\n".join(lines)


def render_face(spec: Dict[str, object]) -> Dict[str, object]:
    font = ImageFont.truetype(str(spec["path"]), int(spec["size"]))
    ascent, descent = font.getmetrics()
    line_height = ascent + descent
    pad = max(4, int(spec["size"]))
    bitmap: List[int] = []
    glyphs: List[Dict[str, int]] = []

    probe = Image.new("L", (pad * 6, pad * 6), 0)
    probe_draw = ImageDraw.Draw(probe)

    sample_width = max(
        1,
        int(math.ceil(probe_draw.textlength("M", font=font))),
    )

    for codepoint in range(ASCII_START, ASCII_END + 1):
        ch = chr(codepoint)
        canvas = Image.new("L", (pad * 6, pad * 6), 0)
        draw = ImageDraw.Draw(canvas)
        baseline = (pad, pad + ascent)
        draw.text(baseline, ch, font=font, fill=255, anchor="ls")
        bbox = canvas.getbbox()
        advance = max(1, int(math.ceil(draw.textlength(ch, font=font))))

        if bbox is None:
            glyphs.append(
                {
                    "offset": len(bitmap),
                    "width": 0,
                    "height": 0,
                    "bearing_x": 0,
                    "bearing_y": 0,
                    "advance": advance,
                }
            )
            continue

        crop = canvas.crop(bbox)
        pixels = list(crop.tobytes())
        glyphs.append(
            {
                "offset": len(bitmap),
                "width": crop.width,
                "height": crop.height,
                "bearing_x": bbox[0] - pad,
                "bearing_y": (pad + ascent) - bbox[1],
                "advance": advance,
            }
        )
        bitmap.extend(pixels)

    return {
        "symbol": spec["symbol"],
        "role": spec["role"],
        "size": spec["size"],
        "line_height": line_height,
        "ascent": ascent,
        "default_advance": sample_width,
        "glyphs": glyphs,
        "bitmap": bitmap,
        "source": Path(spec["path"]).name,
    }


def write_outputs(faces: List[Dict[str, object]]) -> None:
    OUT_H.parent.mkdir(parents=True, exist_ok=True)

    header = """#pragma once

#include <stdint.h>

#include "drivers/font.h"

typedef struct {
    uint32_t bitmap_offset;
    uint16_t width;
    uint16_t height;
    int16_t  bearing_x;
    int16_t  bearing_y;
    uint16_t advance;
} font_asset_glyph_t;

typedef struct {
    font_role_t role;
    uint8_t pixel_size;
    uint8_t line_height;
    uint8_t ascent;
    uint16_t default_advance;
    const font_asset_glyph_t *glyphs;
    const uint8_t *bitmap;
} font_asset_face_t;

extern const font_asset_face_t g_font_asset_faces[];
extern const int g_font_asset_face_count;
"""

    body: List[str] = [
        '#include "assets/font_assets.h"',
        "",
        "/* Generated by scripts/generate_font_assets.py. */",
        "",
    ]

    face_entries: List[str] = []
    for face in faces:
        symbol = face["symbol"]
        body.append(f"/* {face['source']} @ {face['size']} px */")
        body.append(f"static const uint8_t k_font_bitmap_{symbol}[] = {{")
        body.append(c_bytes(face["bitmap"]))
        body.append("};")
        body.append("")
        body.append(f"static const font_asset_glyph_t k_font_glyphs_{symbol}[95] = {{")
        for glyph in face["glyphs"]:
            body.append(
                "    { %d, %d, %d, %d, %d, %d },"
                % (
                    glyph["offset"],
                    glyph["width"],
                    glyph["height"],
                    glyph["bearing_x"],
                    glyph["bearing_y"],
                    glyph["advance"],
                )
            )
        body.append("};")
        body.append("")
        face_entries.append(
            "    { %s, %d, %d, %d, %d, k_font_glyphs_%s, k_font_bitmap_%s },"
            % (
                face["role"],
                face["size"],
                face["line_height"],
                face["ascent"],
                face["default_advance"],
                symbol,
                symbol,
            )
        )

    body.append("const font_asset_face_t g_font_asset_faces[] = {")
    body.extend(face_entries)
    body.append("};")
    body.append("")
    body.append(
        "const int g_font_asset_face_count = (int)(sizeof(g_font_asset_faces) / sizeof(g_font_asset_faces[0]));"
    )
    body.append("")

    OUT_H.write_text(header, encoding="utf-8")
    OUT_C.write_text("\n".join(body), encoding="utf-8")


def main() -> None:
    faces = [render_face(spec) for spec in FONTS]
    write_outputs(faces)
    print(f"Wrote {OUT_H.relative_to(ROOT)} and {OUT_C.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
